obj-y += \
	exit.o \
	open.o \
	write.o \
	fork.o \
	stat.o \
	read.o \
	close.o \
	fstat.o \
	lseek.o \
	ftruncate.o \
	getpid.o \
	syscall_tests.o \
	syscall.o \
	timeofday.o \
	mmap.o \
	mprotect.o \
	munmap.o \
	nanosleep.o \
	mkdir.o \
	gettid.o \
	getcpu.o \
	uname.o \
	sethostname.o \
	syscall_state.o \
	syscall_stubs.o
