#! /usr/bin/sh

source /project/extra/llvm/9.0.0/enable # For Zythos cluster
nwd=$(pwd)
cd ./src/llvm/carat/compiler_passes/nautilus-port # Copy the source into the CAT-c directory
cp ./KARAT.cpp CAT-c/catpass/CatPass.cpp
cp ./CMakeLists.txt CAT-c/catpass/
cp -ar ./src/ CAT-c/catpass/
cp -ar ./include/ CAT-c/catpass/
cd ./CAT-c/ # Execute from top level Makefile
./run_me.sh
cd $nwd # Nautilus working directory --- very suspicious
